services:
  app:
    container_name: momence-fetch-fx
    build: .
    ports:
      - 3010:3010
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017 # docker specific mongodb url
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: momence-fetch-fx-mongo-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
